version: '3.3'

services:
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 9000:80
    environment:
      - PMA_ARBITRARY=1
  site: 
    build: .
    ports :
      - 85:85
    volumes:
      - ./back-end:/var/www/html
      - ./docker/php:/usr/local/etc/php
      - ./docker/apache2/httpd.conf:/etc/apache2/sites-enabled/httpd.conf
      - ./docker/apache2/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/apache2/ports.conf:/etc/apache2/ports.conf
    links:
      - db
  web:
    image: nginx:latest
    volumes:
     - ./front-end/dist:/usr/share/nginx/html
     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 80:80
    environment:
     - NGINX_PORT=80